package org.example.TelegramProject.api;

public enum BotState {
    APART_SEARCH,
    ASK_SUM,

    ASK_DATE_BEGIN,
    ASK_DATE_FINISH,

    APART_INFO_RESPONCE_AWAITING,
    SHOW_USER_PROFILE,
    SHOW_SUBSCRIPTIONS_MENU,

    ASK_TYPE_APART,

    USER_PROFILE,
    PROFILE_FILLED,
    SHOW_MAIN_MENU,
    SHOW_HELP_MENU;
}
