package org.example.TelegramProject.api;

public enum BotState {
    APART_SEARCH,
    APART_SEARCH_STARTED,
    APART_SEARCH_FINISH,
    ASK_SUM_BEGIN,
    ASK_SUM_FINISH,

    ASK_DATE_BEGIN,
    ASK_DATE_FINISH,
    DATE_FINISH_RECEIVED,

    APART_INFO_RESPONCE_AWAITING,
    SHOW_SUBSCRIPTIONS_MENU,
    ASK_SUM_SEARCH,
    SUM_SUM_RECEIVED,
    SUM_SEARCH,

    USER_PROFILE,
    PROFILE_FILLED,
    SHOW_MAIN_MENU,
    SHOW_HELP_MENU;
}
